// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Connect4$Game = require("./Connect4.bs.js");
var CS17SetupGame$Game = require("./CS17SetupGame.bs.js");

function AIPlayer(MyGame) {
  var minimax = function (s, depth) {
    var moves = Curry._1(MyGame.legalMoves, s);
    var stateList = List.map((function (move) {
            return Curry._2(MyGame.nextState, s, move);
          }), moves);
    if (depth === 0) {
      return Curry._1(MyGame.estimateValue, s);
    }
    var x = Curry._1(MyGame.gameStatus, s);
    if (typeof x === "number") {
      return 0.0;
    } else if (x.TAG === /* Win */0) {
      if (x._0 === /* P1 */0) {
        return 50;
      } else {
        return -50;
      }
    } else if (x._0 === /* P1 */0) {
      return List.fold_left((function (prim, prim$1) {
                    if (prim > prim$1) {
                      return prim;
                    } else {
                      return prim$1;
                    }
                  }), -50, List.map((function (state) {
                        return minimax(state, depth - 1 | 0);
                      }), stateList));
    } else {
      return List.fold_left((function (prim, prim$1) {
                    if (prim < prim$1) {
                      return prim;
                    } else {
                      return prim$1;
                    }
                  }), 50, List.map((function (state) {
                        return minimax(state, depth - 1 | 0);
                      }), stateList));
    }
  };
  var bestMove = function (s, _moveList) {
    while(true) {
      var moveList = _moveList;
      if (!moveList) {
        return Pervasives.failwith("cannot find best move");
      }
      var tl = moveList.tl;
      var hd = moveList.hd;
      var $$eval = minimax(Curry._2(MyGame.nextState, s, hd), 3);
      if ($$eval >= bestMove(s, tl)[1]) {
        return [
                hd,
                $$eval
              ];
      }
      _moveList = tl;
      continue ;
    };
  };
  var nextMove = function (s) {
    var moves = Curry._1(MyGame.legalMoves, s);
    return bestMove(s, moves)[0];
  };
  return {
          PlayerGame: MyGame,
          minimax: minimax,
          bestMove: bestMove,
          nextMove: nextMove,
          playerName: "Max and Austin"
        };
}

var MyGame_stringOfPlayer = Connect4$Game.Connect4.stringOfPlayer;

var MyGame_stringOfState = Connect4$Game.Connect4.stringOfState;

var MyGame_stringOfMove = Connect4$Game.Connect4.stringOfMove;

var MyGame_initialState = Connect4$Game.Connect4.initialState;

var MyGame_legalMoves = Connect4$Game.Connect4.legalMoves;

var MyGame_gameStatus = Connect4$Game.Connect4.gameStatus;

var MyGame_nextState = Connect4$Game.Connect4.nextState;

var MyGame_moveOfString = Connect4$Game.Connect4.moveOfString;

var MyGame_estimateValue = Connect4$Game.Connect4.estimateValue;

var MyGame = {
  stringOfPlayer: MyGame_stringOfPlayer,
  stringOfState: MyGame_stringOfState,
  stringOfMove: MyGame_stringOfMove,
  initialState: MyGame_initialState,
  legalMoves: MyGame_legalMoves,
  gameStatus: MyGame_gameStatus,
  nextState: MyGame_nextState,
  moveOfString: MyGame_moveOfString,
  estimateValue: MyGame_estimateValue
};

function minimax(s, depth) {
  var moves = Curry._1(Connect4$Game.Connect4.legalMoves, s);
  var stateList = List.map((function (move) {
          return Curry._2(Connect4$Game.Connect4.nextState, s, move);
        }), moves);
  if (depth === 0) {
    return Curry._1(Connect4$Game.Connect4.estimateValue, s);
  }
  var x = Curry._1(Connect4$Game.Connect4.gameStatus, s);
  if (typeof x === "number") {
    return 0.0;
  } else if (x.TAG === /* Win */0) {
    if (x._0 === /* P1 */0) {
      return 50;
    } else {
      return -50;
    }
  } else if (x._0 === /* P1 */0) {
    return List.fold_left((function (prim, prim$1) {
                  if (prim > prim$1) {
                    return prim;
                  } else {
                    return prim$1;
                  }
                }), -50, List.map((function (state) {
                      return minimax(state, depth - 1 | 0);
                    }), stateList));
  } else {
    return List.fold_left((function (prim, prim$1) {
                  if (prim < prim$1) {
                    return prim;
                  } else {
                    return prim$1;
                  }
                }), 50, List.map((function (state) {
                      return minimax(state, depth - 1 | 0);
                    }), stateList));
  }
}

function bestMove(s, _moveList) {
  while(true) {
    var moveList = _moveList;
    if (!moveList) {
      return Pervasives.failwith("cannot find best move");
    }
    var tl = moveList.tl;
    var hd = moveList.hd;
    var $$eval = minimax(Curry._2(Connect4$Game.Connect4.nextState, s, hd), 3);
    if ($$eval >= bestMove(s, tl)[1]) {
      return [
              hd,
              $$eval
            ];
    }
    _moveList = tl;
    continue ;
  };
}

function nextMove(s) {
  var moves = Curry._1(Connect4$Game.Connect4.legalMoves, s);
  return bestMove(s, moves)[0];
}

var playerName = "Max and Austin";

var TestAIPlayer = {
  PlayerGame: MyGame,
  minimax: minimax,
  bestMove: bestMove,
  nextMove: nextMove,
  playerName: playerName
};

CS17SetupGame$Game.checkExpect(minimax(/* State */{
          _0: {
            TAG: /* Ongoing */1,
            _0: /* P1 */0
          },
          _1: {
            hd: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            },
            tl: {
              hd: {
                hd: -1,
                tl: {
                  hd: 1,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              },
              tl: {
                hd: {
                  hd: -1,
                  tl: {
                    hd: -1,
                    tl: {
                      hd: 1,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                },
                tl: {
                  hd: {
                    hd: 1,
                    tl: {
                      hd: 1,
                      tl: {
                        hd: -1,
                        tl: {
                          hd: 1,
                          tl: {
                            hd: 0,
                            tl: /* [] */0
                          }
                        }
                      }
                    }
                  },
                  tl: {
                    hd: {
                      hd: -1,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: /* [] */0
                            }
                          }
                        }
                      }
                    },
                    tl: {
                      hd: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: {
                                hd: 0,
                                tl: /* [] */0
                              }
                            }
                          }
                        }
                      },
                      tl: {
                        hd: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: {
                                hd: 0,
                                tl: {
                                  hd: 0,
                                  tl: /* [] */0
                                }
                              }
                            }
                          }
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                }
              }
            }
          }
        }, 2), 50, "test minimax favoring P1");

CS17SetupGame$Game.checkExpect(minimax(/* State */{
          _0: {
            TAG: /* Ongoing */1,
            _0: /* P1 */0
          },
          _1: {
            hd: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            },
            tl: {
              hd: {
                hd: -1,
                tl: {
                  hd: 1,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              },
              tl: {
                hd: {
                  hd: -1,
                  tl: {
                    hd: 1,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                },
                tl: {
                  hd: {
                    hd: -1,
                    tl: {
                      hd: 1,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: /* [] */0
                          }
                        }
                      }
                    }
                  },
                  tl: {
                    hd: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: /* [] */0
                            }
                          }
                        }
                      }
                    },
                    tl: {
                      hd: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: {
                                hd: 0,
                                tl: /* [] */0
                              }
                            }
                          }
                        }
                      },
                      tl: {
                        hd: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: {
                                hd: 0,
                                tl: {
                                  hd: 0,
                                  tl: /* [] */0
                                }
                              }
                            }
                          }
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                }
              }
            }
          }
        }, 2), -50, "test minimax favoring P2");

CS17SetupGame$Game.checkExpect(minimax(/* State */{
          _0: {
            TAG: /* Win */0,
            _0: /* P1 */0
          },
          _1: {
            hd: {
              hd: 1,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            },
            tl: {
              hd: {
                hd: -1,
                tl: {
                  hd: 1,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              },
              tl: {
                hd: {
                  hd: -1,
                  tl: {
                    hd: -1,
                    tl: {
                      hd: 1,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                },
                tl: {
                  hd: {
                    hd: 1,
                    tl: {
                      hd: -1,
                      tl: {
                        hd: -1,
                        tl: {
                          hd: 1,
                          tl: {
                            hd: 0,
                            tl: /* [] */0
                          }
                        }
                      }
                    }
                  },
                  tl: {
                    hd: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: /* [] */0
                            }
                          }
                        }
                      }
                    },
                    tl: {
                      hd: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: {
                                hd: 0,
                                tl: /* [] */0
                              }
                            }
                          }
                        }
                      },
                      tl: {
                        hd: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: {
                                hd: 0,
                                tl: {
                                  hd: 0,
                                  tl: /* [] */0
                                }
                              }
                            }
                          }
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                }
              }
            }
          }
        }, 2), 50, "test basecase minimax - Win(P1)");

CS17SetupGame$Game.checkExpect(minimax(/* State */{
          _0: /* Draw */0,
          _1: {
            hd: {
              hd: 1,
              tl: {
                hd: -1,
                tl: {
                  hd: 1,
                  tl: {
                    hd: -1,
                    tl: {
                      hd: 1,
                      tl: /* [] */0
                    }
                  }
                }
              }
            },
            tl: {
              hd: {
                hd: -1,
                tl: {
                  hd: 1,
                  tl: {
                    hd: -1,
                    tl: {
                      hd: 1,
                      tl: {
                        hd: -1,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              },
              tl: {
                hd: {
                  hd: -1,
                  tl: {
                    hd: 1,
                    tl: {
                      hd: -1,
                      tl: {
                        hd: 1,
                        tl: {
                          hd: -1,
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                },
                tl: {
                  hd: {
                    hd: -1,
                    tl: {
                      hd: 1,
                      tl: {
                        hd: -1,
                        tl: {
                          hd: 1,
                          tl: {
                            hd: -1,
                            tl: /* [] */0
                          }
                        }
                      }
                    }
                  },
                  tl: {
                    hd: {
                      hd: 1,
                      tl: {
                        hd: -1,
                        tl: {
                          hd: 1,
                          tl: {
                            hd: -1,
                            tl: {
                              hd: 1,
                              tl: /* [] */0
                            }
                          }
                        }
                      }
                    },
                    tl: {
                      hd: {
                        hd: 1,
                        tl: {
                          hd: -1,
                          tl: {
                            hd: 1,
                            tl: {
                              hd: -1,
                              tl: {
                                hd: 1,
                                tl: /* [] */0
                              }
                            }
                          }
                        }
                      },
                      tl: {
                        hd: {
                          hd: 1,
                          tl: {
                            hd: -1,
                            tl: {
                              hd: 1,
                              tl: {
                                hd: -1,
                                tl: {
                                  hd: 1,
                                  tl: /* [] */0
                                }
                              }
                            }
                          }
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                }
              }
            }
          }
        }, 2), 0.0, "test basecase minimax - Draw");

var TestGame;

var MyAIPlayer = {
  PlayerGame: MyGame,
  nextMove: nextMove,
  playerName: playerName
};

exports.AIPlayer = AIPlayer;
exports.TestGame = TestGame;
exports.TestAIPlayer = TestAIPlayer;
exports.MyAIPlayer = MyAIPlayer;
/*  Not a pure module */
