// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Caml_primitive = require("bs-platform/lib/js/caml_primitive.js");
var CS17SetupGame$Game = require("./CS17SetupGame.bs.js");

function initialState(s) {
  var boardDims = CS17SetupGame$Game.parseBoardDims(s);
  var boardHeight = CS17SetupGame$Game.getBoardHeight(boardDims);
  var boardWidth = CS17SetupGame$Game.getBoardWidth(boardDims);
  var createRow = function (w) {
    if (w !== 0) {
      return {
              hd: 0,
              tl: createRow(w - 1 | 0)
            };
    } else {
      return /* [] */0;
    }
  };
  var createBoard = function (lst, h) {
    if (h !== 0) {
      return {
              hd: lst,
              tl: createBoard(lst, h - 1 | 0)
            };
    } else {
      return /* [] */0;
    }
  };
  return /* State */{
          _0: {
            TAG: /* Ongoing */1,
            _0: /* P1 */0
          },
          _1: createBoard(createRow(boardHeight), boardWidth)
        };
}

function legalMoves(s) {
  var tmp = s._0;
  if (typeof tmp === "number") {
    return /* [] */0;
  }
  if (tmp.TAG === /* Win */0) {
    return /* [] */0;
  }
  var checkRow = function (_lst) {
    while(true) {
      var lst = _lst;
      if (!lst) {
        return false;
      }
      if (lst.hd === 0) {
        return true;
      }
      _lst = lst.tl;
      continue ;
    };
  };
  var checkMatrix = function (_mat, _n) {
    while(true) {
      var n = _n;
      var mat = _mat;
      if (!mat) {
        return /* [] */0;
      }
      var hd = mat.hd;
      if (!hd && !mat.tl) {
        return /* [] */0;
      }
      var tl = mat.tl;
      if (checkRow(hd)) {
        return {
                hd: /* Move */{
                  _0: n
                },
                tl: checkMatrix(tl, n + 1 | 0)
              };
      }
      _n = n + 1 | 0;
      _mat = tl;
      continue ;
    };
  };
  return checkMatrix(s._1, 1);
}

function gameStatus(s) {
  return s._0;
}

function transpose(mat) {
  if (!mat) {
    return Pervasives.failwith("A matrix cannot be 0 - dimensional.");
  }
  var match = mat.hd;
  if (match) {
    if (match.tl) {
      return {
              hd: List.map(List.hd, mat),
              tl: transpose(List.map(List.tl, mat))
            };
    } else {
      return {
              hd: List.flatten(mat),
              tl: /* [] */0
            };
    }
  } else {
    return Pervasives.failwith("A matrix cannot be 0 - dimensional.");
  }
}

function nextState(s, m) {
  var x = s._0;
  if (typeof x === "number") {
    return s;
  }
  if (x.TAG === /* Win */0) {
    return s;
  }
  var y = m._0;
  var x$1 = x._0;
  var disc = x$1 ? -1 : 1;
  var makeMove = function (mat, move, value) {
    if (!mat) {
      return /* [] */0;
    }
    var hd = mat.hd;
    if (!hd && !mat.tl) {
      return /* [] */0;
    }
    var tl = mat.tl;
    var insert = function (lst) {
      if (!lst) {
        return /* [] */0;
      }
      var x = lst.hd;
      if (x !== 0) {
        return {
                hd: x,
                tl: insert(lst.tl)
              };
      } else {
        return {
                hd: value,
                tl: lst.tl
              };
      }
    };
    if ((move - 1 | 0) === 0) {
      return {
              hd: insert(hd),
              tl: tl
            };
    } else {
      return {
              hd: hd,
              tl: makeMove(tl, move - 1 | 0, value)
            };
    }
  };
  var checkFour = function (_lst, discType, _count) {
    while(true) {
      var count = _count;
      var lst = _lst;
      if (count === 4 || count === -4) {
        return true;
      }
      if (!lst) {
        return false;
      }
      var tl = lst.tl;
      if (lst.hd === discType) {
        _count = discType + count | 0;
        _lst = tl;
        continue ;
      }
      _count = 0;
      _lst = tl;
      continue ;
    };
  };
  var checkBoard = function (_mat) {
    while(true) {
      var mat = _mat;
      if (!mat) {
        return false;
      }
      var hd = mat.hd;
      if (!hd && !mat.tl) {
        return false;
      }
      if (checkFour(hd, disc, 0)) {
        return true;
      }
      _mat = mat.tl;
      continue ;
    };
  };
  var checkDiagonal = function (_mat, discType, _count) {
    while(true) {
      var count = _count;
      var mat = _mat;
      if (count === 4) {
        return true;
      }
      if (!mat) {
        return false;
      }
      var match = mat.hd;
      if (!match) {
        return false;
      }
      var tl2 = mat.tl;
      var tl = match.tl;
      var tails = function (_mat) {
        while(true) {
          var mat = _mat;
          if (!mat) {
            return /* [] */0;
          }
          var match = mat.hd;
          if (match) {
            return {
                    hd: match.tl,
                    tl: tails(mat.tl)
                  };
          }
          var tl = mat.tl;
          if (!tl) {
            return /* [] */0;
          }
          _mat = tl;
          continue ;
        };
      };
      if (match.hd === discType) {
        if (checkDiagonal(tails(tl2), discType, count + 1 | 0)) {
          return true;
        }
        if (checkDiagonal({
                hd: tl,
                tl: tails(tl2)
              }, discType, 0)) {
          return true;
        }
        _count = 0;
        _mat = tl2;
        continue ;
      }
      if (checkDiagonal(tails(tl2), discType, 0)) {
        return true;
      }
      if (checkDiagonal({
              hd: tl,
              tl: tails(tl2)
            }, discType, 0)) {
        return true;
      }
      _count = 0;
      _mat = tl2;
      continue ;
    };
  };
  var board = makeMove(s._1, y, disc);
  if (List.length(legalMoves(/* State */{
              _0: {
                TAG: /* Ongoing */1,
                _0: x$1
              },
              _1: board
            })) === 0) {
    return /* State */{
            _0: /* Draw */0,
            _1: board
          };
  } else if (checkFour(List.nth(board, y - 1 | 0), disc, 0) || checkBoard(transpose(board)) || checkDiagonal(board, disc, 0) || checkDiagonal(List.rev(board), disc, 0)) {
    return /* State */{
            _0: {
              TAG: /* Win */0,
              _0: x$1
            },
            _1: board
          };
  } else if (x$1 === /* P1 */0) {
    return /* State */{
            _0: {
              TAG: /* Ongoing */1,
              _0: /* P2 */1
            },
            _1: board
          };
  } else {
    return /* State */{
            _0: {
              TAG: /* Ongoing */1,
              _0: /* P1 */0
            },
            _1: board
          };
  }
}

function currentPlayer(param) {
  var x = param._0;
  if (typeof x === "number") {
    return Pervasives.failwith("neither play wins, its a draw");
  } else {
    return x._0;
  }
}

function estimateValue(inState) {
  var match = inState._0;
  if (typeof match === "number") {
    return 0;
  }
  if (match.TAG === /* Win */0) {
    if (match._0) {
      return -50;
    } else {
      return 50;
    }
  }
  var mat = inState._1;
  var rowValue = function (_lst, _score, disc) {
    while(true) {
      var score = _score;
      var lst = _lst;
      if (!lst) {
        return score;
      }
      var tl = lst.tl;
      var hd1 = lst.hd;
      if (tl) {
        var tl$1 = tl.tl;
        var hd2 = tl.hd;
        if (tl$1) {
          var tl$2 = tl$1.tl;
          var hd3 = tl$1.hd;
          if (tl$2) {
            var tl$3 = tl$2.tl;
            var hd4 = tl$2.hd;
            if (hd1 === hd2 && hd2 === hd3 && hd3 === disc) {
              if (hd4 === 0) {
                _score = Math.imul(15, disc) + score | 0;
                _lst = tl$3;
                continue ;
              }
              _score = Math.imul(3, disc) + score | 0;
              _lst = tl$3;
              continue ;
            }
            _lst = {
              hd: hd2,
              tl: {
                hd: hd3,
                tl: {
                  hd: hd4,
                  tl: tl$3
                }
              }
            };
            continue ;
          }
          if (hd1 === hd2 && hd2 === disc) {
            if (hd3 === 0) {
              _score = Math.imul(5, disc) + score | 0;
              _lst = tl$2;
              continue ;
            }
            _score = Math.imul(3, disc) + score | 0;
            _lst = tl$2;
            continue ;
          }
          _lst = {
            hd: hd2,
            tl: {
              hd: hd3,
              tl: tl$2
            }
          };
          continue ;
        }
        if (hd1 === disc) {
          if (hd2 === 0) {
            _score = disc + score | 0;
            _lst = tl$1;
            continue ;
          }
          _lst = tl$1;
          continue ;
        }
        _lst = {
          hd: hd2,
          tl: tl$1
        };
        continue ;
      }
      _score = score + hd1 | 0;
      _lst = tl;
      continue ;
    };
  };
  var checkDiagonal = function (mat, discType, count) {
    if (!mat) {
      return count;
    }
    var match = mat.hd;
    if (!match) {
      return count;
    }
    var tl2 = mat.tl;
    var tl = match.tl;
    var hd = match.hd;
    var tails = function (_mat) {
      while(true) {
        var mat = _mat;
        if (!mat) {
          return /* [] */0;
        }
        var match = mat.hd;
        if (match) {
          return {
                  hd: match.tl,
                  tl: tails(mat.tl)
                };
        }
        var tl = mat.tl;
        if (!tl) {
          return /* [] */0;
        }
        _mat = tl;
        continue ;
      };
    };
    if (hd === 1) {
      if (count === 0) {
        return Caml_primitive.caml_int_max(Caml_primitive.caml_int_max(checkDiagonal(tails(tl2), discType, count + discType | 0), checkDiagonal({
                            hd: tl,
                            tl: tails(tl2)
                          }, discType, count)), checkDiagonal(tl2, discType, count));
      } else {
        return Caml_primitive.caml_int_max(Caml_primitive.caml_int_max(checkDiagonal(tails(tl2), discType, count + Math.imul(5, discType) | 0), checkDiagonal({
                            hd: tl,
                            tl: tails(tl2)
                          }, discType, count)), checkDiagonal(tl2, discType, count));
      }
    } else if (hd === -1) {
      if (count === 0) {
        return Caml_primitive.caml_int_min(Caml_primitive.caml_int_min(checkDiagonal(tails(tl2), discType, count + discType | 0), checkDiagonal({
                            hd: tl,
                            tl: tails(tl2)
                          }, discType, count)), checkDiagonal(tl2, discType, count));
      } else {
        return Caml_primitive.caml_int_min(Caml_primitive.caml_int_min(checkDiagonal(tails(tl2), discType, count + Math.imul(5, discType) | 0), checkDiagonal({
                            hd: tl,
                            tl: tails(tl2)
                          }, discType, count)), checkDiagonal(tl2, discType, count));
      }
    } else {
      return Caml_primitive.caml_int_max(Caml_primitive.caml_int_max(checkDiagonal(tails(tl2), discType, count), checkDiagonal({
                          hd: tl,
                          tl: tails(tl2)
                        }, discType, count)), checkDiagonal(tl2, discType, count));
    }
  };
  var iterate = function (_mat, _score, disc) {
    while(true) {
      var score = _score;
      var mat = _mat;
      if (!mat) {
        return score;
      }
      _score = score + rowValue(mat.hd, 0, disc) | 0;
      _mat = mat.tl;
      continue ;
    };
  };
  var row1 = iterate(mat, 0, 1);
  var row2 = iterate(mat, 0, -1);
  var col1 = iterate(transpose(mat), 0, 1);
  var col2 = iterate(transpose(mat), 0, -1);
  var diag1 = checkDiagonal(mat, 0, 1);
  var diag2 = checkDiagonal(mat, 0, -1);
  var diag3 = checkDiagonal(List.rev(mat), 0, 1);
  var diag4 = checkDiagonal(List.rev(mat), 0, -1);
  return Caml_primitive.caml_int_max(Caml_primitive.caml_int_max(row1 > col1 ? row1 : col1, diag1), diag3) + Caml_primitive.caml_int_min(Caml_primitive.caml_int_min(row2 < col2 ? row2 : col2, diag2), diag4);
}

function stringOfPlayer(param) {
  if (param) {
    return "P2";
  } else {
    return "P1";
  }
}

function stringOfState(param) {
  var tmp = param._0;
  if (typeof tmp === "number") {
    return "Game Over";
  }
  if (tmp.TAG === /* Win */0) {
    return "Game Over";
  }
  var printBoard = function (lst) {
    if (!lst) {
      return "";
    }
    var match = lst.hd;
    if (match) {
      var tl2 = lst.tl;
      var tl = match.tl;
      var hd = match.hd;
      if (hd === 1) {
        return " | + | " + printBoard({
                    hd: tl,
                    tl: tl2
                  });
      } else if (hd === 0) {
        return " | O | " + printBoard({
                    hd: tl,
                    tl: tl2
                  });
      } else {
        return " | - | " + printBoard({
                    hd: tl,
                    tl: tl2
                  });
      }
    }
    var tl$1 = lst.tl;
    if (tl$1) {
      return "\n\n" + printBoard(tl$1);
    } else {
      return "";
    }
  };
  return "Board: \n" + printBoard(List.rev(transpose(param._1)));
}

function stringOfMove(x) {
  return String(x._0);
}

function moveOfString(str, st) {
  var isInteger = function (s) {
    try {
      return Caml_format.caml_int_of_string(s);
    }
    catch (exn){
      return Pervasives.failwith("input has to be an integer");
    }
  };
  var move = isInteger(str);
  if (List.mem(/* Move */{
          _0: move
        }, legalMoves(st))) {
    return /* Move */{
            _0: move
          };
  } else {
    return Pervasives.failwith("invalid move");
  }
}

var Connect4 = {
  initialState: initialState,
  legalMoves: legalMoves,
  gameStatus: gameStatus,
  transpose: transpose,
  nextState: nextState,
  currentPlayer: currentPlayer,
  estimateValue: estimateValue,
  stringOfPlayer: stringOfPlayer,
  stringOfState: stringOfState,
  stringOfMove: stringOfMove,
  moveOfString: moveOfString
};

CS17SetupGame$Game.checkExpect(legalMoves(initialState("5 7")), {
      hd: /* Move */{
        _0: 1
      },
      tl: {
        hd: /* Move */{
          _0: 2
        },
        tl: {
          hd: /* Move */{
            _0: 3
          },
          tl: {
            hd: /* Move */{
              _0: 4
            },
            tl: {
              hd: /* Move */{
                _0: 5
              },
              tl: {
                hd: /* Move */{
                  _0: 6
                },
                tl: {
                  hd: /* Move */{
                    _0: 7
                  },
                  tl: /* [] */0
                }
              }
            }
          }
        }
      }
    }, "Successfully found all legal moves!");

CS17SetupGame$Game.checkExpect(nextState(initialState("1 3"), /* Move */{
          _0: 1
        }), /* State */{
      _0: {
        TAG: /* Ongoing */1,
        _0: /* P2 */1
      },
      _1: {
        hd: {
          hd: 1,
          tl: /* [] */0
        },
        tl: {
          hd: {
            hd: 0,
            tl: /* [] */0
          },
          tl: {
            hd: {
              hd: 0,
              tl: /* [] */0
            },
            tl: /* [] */0
          }
        }
      }
    }, "Successfully made a move!");

console.log(stringOfState(initialState("5 7")));

var board1 = /* State */{
  _0: {
    TAG: /* Ongoing */1,
    _0: /* P1 */0
  },
  _1: {
    hd: {
      hd: 0,
      tl: {
        hd: 0,
        tl: {
          hd: 0,
          tl: {
            hd: 0,
            tl: {
              hd: 0,
              tl: /* [] */0
            }
          }
        }
      }
    },
    tl: {
      hd: {
        hd: 0,
        tl: {
          hd: 0,
          tl: {
            hd: 0,
            tl: {
              hd: 0,
              tl: {
                hd: 0,
                tl: /* [] */0
              }
            }
          }
        }
      },
      tl: {
        hd: {
          hd: 0,
          tl: {
            hd: 0,
            tl: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: /* [] */0
                }
              }
            }
          }
        },
        tl: {
          hd: {
            hd: 0,
            tl: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: /* [] */0
                  }
                }
              }
            }
          },
          tl: {
            hd: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            },
            tl: {
              hd: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              },
              tl: {
                hd: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                },
                tl: /* [] */0
              }
            }
          }
        }
      }
    }
  }
};

CS17SetupGame$Game.checkExpect(nextState(board1, /* Move */{
          _0: 4
        }), /* State */{
      _0: {
        TAG: /* Ongoing */1,
        _0: /* P2 */1
      },
      _1: {
        hd: {
          hd: 0,
          tl: {
            hd: 0,
            tl: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: /* [] */0
                }
              }
            }
          }
        },
        tl: {
          hd: {
            hd: 0,
            tl: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: /* [] */0
                  }
                }
              }
            }
          },
          tl: {
            hd: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            },
            tl: {
              hd: {
                hd: 1,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              },
              tl: {
                hd: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                },
                tl: {
                  hd: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: /* [] */0
                          }
                        }
                      }
                    }
                  },
                  tl: {
                    hd: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: /* [] */0
                            }
                          }
                        }
                      }
                    },
                    tl: /* [] */0
                  }
                }
              }
            }
          }
        }
      }
    }, "Success! Player 1 made a move in column 4!");

var board3 = /* State */{
  _0: {
    TAG: /* Ongoing */1,
    _0: /* P1 */0
  },
  _1: {
    hd: {
      hd: 0,
      tl: {
        hd: 0,
        tl: {
          hd: 0,
          tl: {
            hd: 0,
            tl: {
              hd: 0,
              tl: /* [] */0
            }
          }
        }
      }
    },
    tl: {
      hd: {
        hd: 0,
        tl: {
          hd: 0,
          tl: {
            hd: 0,
            tl: {
              hd: 0,
              tl: {
                hd: 0,
                tl: /* [] */0
              }
            }
          }
        }
      },
      tl: {
        hd: {
          hd: 0,
          tl: {
            hd: 0,
            tl: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: /* [] */0
                }
              }
            }
          }
        },
        tl: {
          hd: {
            hd: -1,
            tl: {
              hd: 1,
              tl: {
                hd: 1,
                tl: {
                  hd: 1,
                  tl: {
                    hd: 0,
                    tl: /* [] */0
                  }
                }
              }
            }
          },
          tl: {
            hd: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            },
            tl: {
              hd: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              },
              tl: {
                hd: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                },
                tl: /* [] */0
              }
            }
          }
        }
      }
    }
  }
};

CS17SetupGame$Game.checkExpect(nextState(board3, /* Move */{
          _0: 4
        }), /* State */{
      _0: {
        TAG: /* Win */0,
        _0: /* P1 */0
      },
      _1: {
        hd: {
          hd: 0,
          tl: {
            hd: 0,
            tl: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: /* [] */0
                }
              }
            }
          }
        },
        tl: {
          hd: {
            hd: 0,
            tl: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: /* [] */0
                  }
                }
              }
            }
          },
          tl: {
            hd: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            },
            tl: {
              hd: {
                hd: -1,
                tl: {
                  hd: 1,
                  tl: {
                    hd: 1,
                    tl: {
                      hd: 1,
                      tl: {
                        hd: 1,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              },
              tl: {
                hd: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                },
                tl: {
                  hd: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: /* [] */0
                          }
                        }
                      }
                    }
                  },
                  tl: {
                    hd: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: /* [] */0
                            }
                          }
                        }
                      }
                    },
                    tl: /* [] */0
                  }
                }
              }
            }
          }
        }
      }
    }, "Success! Player 1 won!");

var board4 = /* State */{
  _0: {
    TAG: /* Ongoing */1,
    _0: /* P1 */0
  },
  _1: {
    hd: {
      hd: 0,
      tl: {
        hd: 0,
        tl: {
          hd: 0,
          tl: {
            hd: 0,
            tl: {
              hd: 0,
              tl: /* [] */0
            }
          }
        }
      }
    },
    tl: {
      hd: {
        hd: -1,
        tl: {
          hd: 1,
          tl: {
            hd: 0,
            tl: {
              hd: 0,
              tl: {
                hd: 0,
                tl: /* [] */0
              }
            }
          }
        }
      },
      tl: {
        hd: {
          hd: -1,
          tl: {
            hd: -1,
            tl: {
              hd: 1,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: /* [] */0
                }
              }
            }
          }
        },
        tl: {
          hd: {
            hd: -1,
            tl: {
              hd: -1,
              tl: {
                hd: -1,
                tl: {
                  hd: 1,
                  tl: {
                    hd: 0,
                    tl: /* [] */0
                  }
                }
              }
            }
          },
          tl: {
            hd: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            },
            tl: {
              hd: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              },
              tl: {
                hd: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                },
                tl: /* [] */0
              }
            }
          }
        }
      }
    }
  }
};

CS17SetupGame$Game.checkExpect(nextState(board4, /* Move */{
          _0: 1
        }), /* State */{
      _0: {
        TAG: /* Win */0,
        _0: /* P1 */0
      },
      _1: {
        hd: {
          hd: 1,
          tl: {
            hd: 0,
            tl: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: /* [] */0
                }
              }
            }
          }
        },
        tl: {
          hd: {
            hd: -1,
            tl: {
              hd: 1,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: /* [] */0
                  }
                }
              }
            }
          },
          tl: {
            hd: {
              hd: -1,
              tl: {
                hd: -1,
                tl: {
                  hd: 1,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            },
            tl: {
              hd: {
                hd: -1,
                tl: {
                  hd: -1,
                  tl: {
                    hd: -1,
                    tl: {
                      hd: 1,
                      tl: {
                        hd: 0,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              },
              tl: {
                hd: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                },
                tl: {
                  hd: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: /* [] */0
                          }
                        }
                      }
                    }
                  },
                  tl: {
                    hd: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: /* [] */0
                            }
                          }
                        }
                      }
                    },
                    tl: /* [] */0
                  }
                }
              }
            }
          }
        }
      }
    }, "Success! Player 1 won!");

CS17SetupGame$Game.checkExpect(nextState(board4, /* Move */{
          _0: 5
        }), /* State */{
      _0: {
        TAG: /* Ongoing */1,
        _0: /* P2 */1
      },
      _1: {
        hd: {
          hd: 0,
          tl: {
            hd: 0,
            tl: {
              hd: 0,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: /* [] */0
                }
              }
            }
          }
        },
        tl: {
          hd: {
            hd: -1,
            tl: {
              hd: 1,
              tl: {
                hd: 0,
                tl: {
                  hd: 0,
                  tl: {
                    hd: 0,
                    tl: /* [] */0
                  }
                }
              }
            }
          },
          tl: {
            hd: {
              hd: -1,
              tl: {
                hd: -1,
                tl: {
                  hd: 1,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            },
            tl: {
              hd: {
                hd: -1,
                tl: {
                  hd: -1,
                  tl: {
                    hd: -1,
                    tl: {
                      hd: 1,
                      tl: {
                        hd: 0,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              },
              tl: {
                hd: {
                  hd: 1,
                  tl: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                },
                tl: {
                  hd: {
                    hd: 0,
                    tl: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: /* [] */0
                          }
                        }
                      }
                    }
                  },
                  tl: {
                    hd: {
                      hd: 0,
                      tl: {
                        hd: 0,
                        tl: {
                          hd: 0,
                          tl: {
                            hd: 0,
                            tl: {
                              hd: 0,
                              tl: /* [] */0
                            }
                          }
                        }
                      }
                    },
                    tl: /* [] */0
                  }
                }
              }
            }
          }
        }
      }
    }, "Success! Player 1 made a move in column 5!");

CS17SetupGame$Game.checkExpect(transpose({
          hd: {
            hd: 1,
            tl: /* [] */0
          },
          tl: {
            hd: {
              hd: 2,
              tl: /* [] */0
            },
            tl: {
              hd: {
                hd: 3,
                tl: /* [] */0
              },
              tl: /* [] */0
            }
          }
        }), {
      hd: {
        hd: 1,
        tl: {
          hd: 2,
          tl: {
            hd: 3,
            tl: /* [] */0
          }
        }
      },
      tl: /* [] */0
    }, "Transposed successfully on a 3x1 column (base case)");

CS17SetupGame$Game.checkExpect(transpose({
          hd: {
            hd: 1,
            tl: {
              hd: 7,
              tl: /* [] */0
            }
          },
          tl: {
            hd: {
              hd: 10,
              tl: {
                hd: 11,
                tl: /* [] */0
              }
            },
            tl: /* [] */0
          }
        }), {
      hd: {
        hd: 1,
        tl: {
          hd: 10,
          tl: /* [] */0
        }
      },
      tl: {
        hd: {
          hd: 7,
          tl: {
            hd: 11,
            tl: /* [] */0
          }
        },
        tl: /* [] */0
      }
    }, "Transposed successfully on a 2 x 3 matrix");

CS17SetupGame$Game.checkExpect(transpose({
          hd: {
            hd: 1,
            tl: {
              hd: 2,
              tl: {
                hd: 3,
                tl: /* [] */0
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        hd: 1,
        tl: /* [] */0
      },
      tl: {
        hd: {
          hd: 2,
          tl: /* [] */0
        },
        tl: {
          hd: {
            hd: 3,
            tl: /* [] */0
          },
          tl: /* [] */0
        }
      }
    }, "Transposed successfully on a 1x3 row");

var MyGame = {
  stringOfPlayer: stringOfPlayer,
  stringOfState: stringOfState,
  stringOfMove: stringOfMove,
  initialState: initialState,
  legalMoves: legalMoves,
  gameStatus: gameStatus,
  nextState: nextState,
  moveOfString: moveOfString,
  estimateValue: estimateValue
};

exports.Connect4 = Connect4;
exports.MyGame = MyGame;
exports.board1 = board1;
exports.board3 = board3;
exports.board4 = board4;
/*  Not a pure module */
